### ISSUE TITLE
Feature: support file uploads

### ISSUE THREAD

**Issue by daun** [swup/forms-plugin#53]
**Describe the problem**

We should go ahead and implement file uploads — it's simple enough with `fetch` now.

**Describe the proposed solution**

Append attached files to the request body:

```js
const input = document.querySelector('input[type="file"]')
const data = new FormData()
for (const file of input.files) {
  data.append(input.name, file)
}

fetch('/', { method: 'POST', body: data })
```

**Alternatives considered**

Keep recommending to use the API directly for file uploads.

**How important is this feature to you?**

- [x] Nice to have
- [ ] Would make my life a lot easier
- [ ] I cannot use swup without it

**Comment by daun** [comment]
Looks like this is already supported :) Creating a `FormData` obj from a `form` element apparently includes file inputs.

**Comment by hirasso** [comment]
I remember a bug in Safari where [empty file inputs in AJAX-submitted forms would cause the request to fail](https://stackoverflow.com/a/49711062/586823). Back then I used [this hack](https://stackoverflow.com/a/49711062/586823) to fix the issue.

We should test sometime if this problem was solved in recent versions of Safari.

Should I create an issue for this?

**Comment by daun** [comment]
Let‘s maybe just reopen this issue to keep track of it? And test in Safari. Could this have to do with XMLHttpRequest instrad of fetch? In any case, let‘s make sure!

**Comment by hirasso** [comment]
It could, yes! Need a project to test it 😅

**Comment by daun** [comment]
I think we're safe — looks like the issue [was solved](https://trac.webkit.org/changeset/230963/webkit) in a Safari release in 2018, i.e. it only affects Safari 11 which we currently don't support.
